# Generated by Django 4.0.5 on 2022-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('apepat', models.CharField(max_length=30)),
                ('apemat', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
